"""
guide_saver.py

Responsible for ONE thing only: saving AI-generated travel content
(checklists, guides, comparisons) to a local file so the user can
access it later.

Does NOT generate content — only handles storage (data persistence).
"""

from pathlib import Path


def save_guide(content: str, filename: str) -> str:
    """
    Save AI-generated text to a .txt file inside saved_guides/.

    Parameters:
        content (str): The text generated by Gemini (response.text)
        filename (str): Name of the file e.g. "Japan.txt"

    Returns:
        str: Confirmation message once the file is saved.
    """
    # Step 2: Create storage folder
    folder = Path("saved_guides")
    folder.mkdir(exist_ok=True)

    # Step 3+4: Build full file path
    file_path = folder / filename

    # Step 5: Write to file (creates or overwrites)
    file_path.write_text(content, encoding="utf-8")

    # Step 6: Return confirmation
    return "Guide saved successfully"


def list_saved_guides() -> list:
    """Return all .txt filenames inside saved_guides/."""
    folder = Path("saved_guides")
    if not folder.exists():
        return []
    return sorted([f.name for f in folder.iterdir() if f.suffix == ".txt"])


def load_saved_guide(filename: str) -> str:
    """Read back a saved guide .txt file."""
    return (Path("saved_guides") / filename).read_text(encoding="utf-8")
